### ISSUE TITLE
change serial number ?

### ISSUE THREAD

**Issue by gmat** [zwizwa/usb_relay_ch551g#1]
Hi,
many thanks for your readme. I get the instructions to action the relay.
My next problem is that I've got 3 same cards, same Manufacturer name, same Product and badly same serial number. How to identify each card ?
Is there a way to change permanently the serial number ? 
If not, do you know if it's possible to assign a plugged device on a specific usb host port to a specific device path (linux of course) ?
Or do you know some other solution(s) in that kind of problem ?
Thanks for your help,

**Comment by zwizwa** [comment]
I'm not aware of any way to change the serial number. I think device path is the best option. Try something like this:

basename $(readlink -f /sys/class/hidraw/hidraw0/device/../..)

**Comment by gmat** [comment]
ok thanks for your help. I close this.

**Comment by gmat** [comment]
ok thanks for your help. I close this.
